
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - name: Checkout different repository
              uses: actions/checkout@v4
              with:
                  repository: 'JinPlanter/Pharma-Assist'
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Run CI command
              run: npm ci
            - name: Test
              run: npm test
            - name: Build
              env:
                MONGODB_URI: ${{ secrets.MONGODB_URI }}
              run: npm run build
              

            