
name: Test App

on:
  push:
    branches:
      - test-cypress
  pull_request:
    branches:
      - master
  
jobs:
  unit-tests:
    name: Run Unit and Component Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:coverage
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path:  |
            coverage/
            